version: "3.8"

x-restart-policy:
  &restart_policy
  restart: unless-stopped

services:

  consul:
    image: hashicorp/consul:1.11
    container_name: consul
    restart: always
    volumes:
      - ./configs/consul/config.hcl:/consul/config/server.hcl:ro
      - "./configs/consul:/scripts"
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    command:
      [
        "consul",
        "agent",
        "-config-file=/consul/config/server.hcl",
        "-config-dir=/consul/config"
      ]
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  ingress:
    image: nicholasjackson/consul-envoy:v1.11.2-v1.20.1
    container_name: ingress
    depends_on:
      - "web"
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      CENTRAL_CONFIG_DIR: "/central"
    volumes:
      - "./configs/ingress:/scripts"
      - "./configs/central:/central"
    command: [ "/bin/sh", "/scripts/entrypoint-gw.sh" ]
    ports:
      - 8080:8080
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  web:
    image: nicholasjackson/fake-service:vm-v1.10.7-v0.22.7
    container_name: web
    restart: always
    depends_on:
      - "consul"
    environment:
      CONSUL_SERVER: 10.5.0.2
      CONSUL_DATACENTER: "dc1"
      SERVICE_ID: "web-v1"
      SERVICE_CONFIG: /config/web-1.hcl
      # CENTRAL_CONFIG: "/central/web_defaults.hcl"
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: "http://localhost:9091"
      MESSAGE: "Web response"
      NAME: "Web"
      SERVER_TYPE: "http"
      HTTP_CLIENT_APPEND_REQUEST: "true"
    volumes:
      - "./configs/web:/config"
      # - "./configs/central:/central"
    ports:
      - 9091:9090
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  api:
    image: nicholasjackson/fake-service:vm-v1.10.7-v0.22.7
    container_name: api
    depends_on:
      - "consul"
    environment:
      CONSUL_SERVER: 10.5.0.2
      CONSUL_DATACENTER: "dc1"
      SERVICE_ID: "api-v1"
      SERVICE_CONFIG: /config/api-1.hcl
      # CENTRAL_CONFIG: "/central/api_defaults.hcl"
      LISTEN_ADDR: 0.0.0.0:9090
      MESSAGE: "API response"
      NAME: "Api"
      SERVER_TYPE: "http"
    volumes:
      - "./configs/api:/config"
      # - "./configs/central:/central"
    ports:
      - 9092:9090
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
